baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Group 4'
theme = "ananke"

[markup.goldmark.renderer]
  unsafe = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/whitman-joyner/ict302-4"
follow = true